import { cldImg } from '@/src/utils/cloudinary'

export const ASSETS = {
  // portada desktop
  hero: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-portada-desktop_dsfg26'),
  // portada mobile
  heroMobile: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-portada-mobile_szfnqm'),
  // imágenes
  img1: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-1_uaw9lv'),
  img2: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-2_muytic'),
  img3: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-3_yutp1a'),
  img4: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-4_pptqla'),
  img5: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-5_flbwsi'),
  img6: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-6_h9gjd7'),
  img7: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-7_jdpgrw'),
  img8: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-8_qek0ug'),
  img9: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-9_rhnpuw'),
  img10: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-10_vuxg8z'),
  img11: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-11_qypfgd'),
  img12: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-12_kazkok'),
  img13: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-13_o32hrc'),
  img14: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-14_epalvu'),
  img15: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-15_xskhpn'),
  img16: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-16_vsyype'),
  img17: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-17_jmf1ms'),
  img18: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-18_t0fmko'),
  img19: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-19_qjz7h1 q'),
  img20: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-20_m2dkmh'),
  img21: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-21_fdqruz'),
  img22: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-22_ynf7wj'),
  img23: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-23_xpb3ot'),
  img24: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-24_bjyixb'),
  // carousel1 (vertical 442x662)
  carousel1: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-1_cg81dv', 'h_330,c_scale'),
  carousel2: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-2_ct7dln', 'h_330,c_scale'),
  carousel3: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-3_re9jzu', 'h_330,c_scale'),
  carousel4: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-4_yb1ave', 'h_330,c_scale'),
  carousel5: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-5_tzamu4', 'h_330,c_scale'),
  carousel6: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-6_oohr5a', 'h_330,c_scale'),
  carousel7: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-7_wjtex9', 'h_330,c_scale'),
  carousel8: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-8_cq7grp', 'h_330,c_scale'),
  carousel9: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-9_p6edgc', 'h_330,c_scale'),
  carousel10: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel1-10_uocxgj', 'h_330,c_scale'),
  // carousel2 (horizontal 1176x662)
  carousel11: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-1_pianxc', 'h_330,c_scale'),
  carousel12: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-2_kdaggy', 'h_330,c_scale'),
  carousel13: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-3_lifhgy', 'h_330,c_scale'),
  carousel14: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-4_gp540l', 'h_330,c_scale'),
  carousel15: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-5_dbspz3', 'h_330,c_scale'),
  carousel16: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-6_opb2uf', 'h_330,c_scale'),
  carousel17: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-7_upsi2a', 'h_330,c_scale'),
  carousel18: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-8_tfmumr', 'h_330,c_scale'),
  carousel19: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-9_lmlmut', 'h_330,c_scale'),
  carousel20: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-10_f02wtn', 'h_330,c_scale'),
  carousel21: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-11_plwxpe', 'h_330,c_scale'),
  carousel22: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-12_yupgah', 'h_330,c_scale'),
  carousel23: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-13_ot5iqg', 'h_330,c_scale'),
  carousel24: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-14_eh59uz', 'h_330,c_scale'),
  carousel25: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-15_rupbk3', 'h_330,c_scale'),
  carousel26: cldImg('CONSTANZASCHWARTZ-projects-masalladelinfinito-carrousel2-16_imlp86', 'h_330,c_scale'),
} as const