// Generates tiny blurred LQIP (Low-Quality Image Placeholders) for every carousel
// image and writes them to src/data/lqip.ts as a pathname → data-URI map.
//
// Run once after carousel assets change:  node scripts/gen-lqip.mjs
// Requires the dev dependency `sharp`. The output is committed; sharp is NOT
// needed at app build time.

import sharp from 'sharp'
import { writeFile } from 'node:fs/promises'

const BASE = 'https://pub-c45392de4794447390623deb4dca4edd.r2.dev'

// Mirror of projectR2's carousel layout. Each entry expands to the WebP carousel
// files that exist in R2 (verified). Names match <stem>-<name>.webp under <sub>.
const r2 = (folder, sub, stem, name) =>
  `${BASE}/${['PROJECTS', folder, 'IMGS', 'WEBp', sub, `${stem}-${name}.webp`]
    .filter(Boolean)
    .map(encodeURIComponent)
    .join('/')}`

const range = (n) => Array.from({ length: n }, (_, i) => i + 1)

const urls = []

// design-week — single CARROUSEL/, carrousel-1..6
{
  const f = 'DESIGN WEEK MEXICO'
  const s = 'CONSTANZASCHWARTZ-projects-designweekmexico'
  range(6).forEach((n) => urls.push(r2(f, 'CARROUSEL', s, `carrousel-${n}`)))
}
// eco — CARROUSEL 1 (1..5) + CARROUSEL 2 (1..6)
{
  const f = 'ECO AL INFINITO'
  const s = 'CONSTANZASCHWARTZ-projects-ecoalinfinito'
  range(5).forEach((n) => urls.push(r2(f, 'CARROUSEL 1', s, `carrousel1-${n}`)))
  range(6).forEach((n) => urls.push(r2(f, 'CARROUSEL 2', s, `carrousel2-${n}`)))
}
// mas-alla — CARROUSEL 1 (1..10) + CARROUSEL 2 (1..16)
{
  const f = 'MAS ALLA DEL INFINITO'
  const s = 'CONSTANZASCHWARTZ-projects-masalladelinfinito'
  range(10).forEach((n) => urls.push(r2(f, 'CARROUSEL 1', s, `carrousel1-${n}`)))
  range(16).forEach((n) => urls.push(r2(f, 'CARROUSEL 2', s, `carrousel2-${n}`)))
}
// mutek — single CARROUSEL/, carrousel-1..7
{
  const f = 'MUTEK'
  const s = 'CONSTANZASCHWARTZ-projects-Mutek'
  range(7).forEach((n) => urls.push(r2(f, 'CARROUSEL', s, `carrousel-${n}`)))
}

async function lqipFor(url) {
  const res = await fetch(url)
  if (!res.ok) throw new Error(`${res.status} ${url}`)
  const buf = Buffer.from(await res.arrayBuffer())
  const out = await sharp(buf)
    .resize(24, null, { fit: 'inside' }) // ~24px wide, keeps aspect
    .blur(1.2)
    .webp({ quality: 35 })
    .toBuffer()
  return `data:image/webp;base64,${out.toString('base64')}`
}

const map = {}
let ok = 0
for (const url of urls) {
  try {
    const key = new URL(url).pathname // encoded pathname, matches Carousel's new URL(src).pathname
    map[key] = await lqipFor(url)
    ok++
    process.stdout.write('.')
  } catch (e) {
    console.error('\nFAILED', e.message)
  }
}

const body = `// AUTO-GENERATED by scripts/gen-lqip.mjs — do not edit by hand.
// Pathname → tiny blurred WebP data URI, shown instantly under each carousel
// image until the full image decodes.

export const LQIP: Record<string, string> = ${JSON.stringify(map, null, 2)}
`

await writeFile(new URL('../src/data/lqip.ts', import.meta.url), body)
console.log(`\nWrote src/data/lqip.ts — ${ok}/${urls.length} placeholders.`)
